### ISSUE TITLE
Getting pna.nextTick is not a function with node 8.12.0

### ISSUE THREAD

**Issue by mrchief** [jorgebucaran/nvm.fish#72]
Steps to repro:

```
> fnm 8.12.0

> npm i eslint -D                                // eslint is just an example. Happens with any package. Or even doing npm i twice throws the same error

```

You get `pna.nextTick is not a function` error. The same thing works fine with v8.11.4. I've tried cleaning node_modules and stuff but the error remains.

**Comment by saintwinkle** [comment]
See #68 , may solve the issue.

**Comment by jorgebucaran** [comment]
#68 was merged so we can close.
